### ISSUE TITLE
Delay ?

### ISSUE THREAD

**Issue by trebmuh** [brummer10/screcord.lv2#1]
Hi Hermann. Another great little application, thanks for this.
I just saw while looking at it in jalv.select, that it's indicating screcord as a delay (while mouseovering in the jalv.select list).
Looking quickly at the code, it does look like it's defined in sc_record.ttl two times once on line 35 and once on line 96 (I guess, once for the mono plugin and once for the stereo).
Could this be something else fitting a bit better to the actual purpose of screcord?

**Comment by brummer10** [comment]
Hi

Will have a look as soon I could.

**Comment by brummer10** [comment]
Hi
I've looked at the LV2 plugin specs, and the only one which seems to fit a bit better is the Utility category, which I've set now. It seems screcord is the one and only record plugin in the lv2 world. 

regards
hermann

**Comment by trebmuh** [comment]
Sweat, thanks for having kept me in the loop.
Cheers.

**Comment by trebmuh** [comment]
For the curious readers, the different LV2 categories can be found here : http://lv2plug.in/ns/lv2core/
