### ISSUE TITLE
Segfault, missing make_path(NULL) in constructor.

### ISSUE THREAD

**Issue by Stazed** [brummer10/screcord.lv2#12]
If the host does not support LV2_STATE__makePath feature, the segfault
occurs in: inline std::string SCapture::get_ffilename().
The,  if (make_path) {} succeeds because of the missing NULL initializer.

Adding: make_path(NULL),  to SCrecord() constructor fixed it for me.

Thank you for this very useful plugin!!

**Comment by brummer10** [comment]
Yes, that makes sense, should be fixed now.

**Comment by Stazed** [comment]
Yes, works now.

**Comment by Stazed** [comment]
Found another one of these when using the custom UI.  In **sc_record_x11ui.c**, getting a segfault in:
>static void show_path(void *w_, void* user_data) 
if (ui->make_path) - line 183.

ui->make_path does not get initialized to NULL in LV2UI_Handle instantiate() if the features check fails.
>if (!strcmp(features[i]->URI, LV2_STATE__makePath))

Adding:
> ui->make_path = NULL;
at line 221 fixes it.

**Comment by brummer10** [comment]
Hi
Yes, it's already there. You just need to update your checkout. 
Bonus: you'll find a new quad recorder after update. 
regards
hermann

**Comment by Stazed** [comment]
What an idiot I am!! Sorry for the noise. 
Thanks!!!
