### ISSUE TITLE
Could you please add the license?

### ISSUE THREAD

**Issue by yurivict** [brummer10/screcord.lv2#4]
Packagers usually need license to be specified.

**Comment by trebmuh** [comment]
It would be even better, yes. In the meantime, @yurivict we can check the headers of the 4 files screcord is made with, then we can see it's GPL 2+.

**Comment by yurivict** [comment]
The only dependency, libsndfile, is LGPL21.

**Comment by trebmuh** [comment]
I was referring to the [4 files from screcord sources](https://github.com/brummer10/screcord.lv2), not the dependencies.

**Comment by yurivict** [comment]
They all say they are GPL. Should be ok to add GPL2.

**Comment by trebmuh** [comment]
Yes, they all says that it's GPL 2+, hence one can package it.

**Comment by yurivict** [comment]
I never doubted this, but projects usually have a license file attached.

**Comment by trebmuh** [comment]
I guess that for bigger project when there are a lot of files, it make sense to add a license file to get straight to the point, avoiding the user/packager to check every file's header, that said (as a packager), I don't mind browsing 4 files to check the license in the headers.

Anyway, leaving that to brummer now :)

**Comment by brummer10** [comment]
done
