### ISSUE TITLE
Add a save dir string exposed as lv2 preset option

### ISSUE THREAD

**Issue by Baggypants** [brummer10/screcord.lv2#8]
My idea is that someone could create an lv2 preset where the save directory is set. Then different presets would have different save locations. Useful if there are multiple places to save to depending on what you have plugged in.

**Comment by brummer10** [comment]
what special use-case do you've in mind?

**Comment by Baggypants** [comment]
I'm using the plug in as part of the [zynthian](http://zynthian.org) raspberry pi synth project. It uses jalv as the plugin host and presents it's own python interface to the plugin. There could be multiple USB storage devices attached and mounted in different places.

Edit: it compiles very cleanly for arm btw, thanks for that!

**Comment by brummer10** [comment]
I guess then you using ( or should use) this fork:
https://github.com/brkl/screcord.lv2
which provide automatically USB storage support.

**Comment by Baggypants** [comment]
Perfect!
